phpcs updated

diff --git a/.ddev/commands/web/phpcs b/.ddev/commands/web/phpcs
--- a/.ddev/commands/web/phpcs
+++ b/.ddev/commands/web/phpcs
@@ -6,12 +6,12 @@
 
 phpcs --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme --ignore=node_modules "$@"
 
-# exit=$?
+exit=$?
 
-# # Exit code 0 is important for the pre-commit hook to work.
-# # See https://github.com/squizlabs/PHP_CodeSniffer/issues/1818
-# if [[ $exit -eq 0 || $exit -eq 1 ]]; then
-#     exit 0
-# fi
+# Exit code 0 is important for the pre-commit hook to work.
+# See https://github.com/squizlabs/PHP_CodeSniffer/issues/1818
+if [[ $exit -eq 0 || $exit -eq 1 ]]; then
+    exit 0
+fi
 
-# exit $exit
+exit $exit
